FROM node:25-slim

RUN apt-get update && apt-get install -y \
    python3 \
    make \
    g++ \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN git config --global --add safe.directory /app

WORKDIR /app
