// Move descriptions and stats for display in the TM Shop
// Base power and category sourced from Gen IV data

export interface MoveInfo {
  bp: number;
  category: 'Physical' | 'Special' | 'Status';
  description: string;
}

export const MOVE_INFO: Record<string, MoveInfo> = {
  'Aerial Ace':     { bp: 60,  category: 'Physical', description: 'An extremely fast attack that never misses.' },
  'Acid Armor':     { bp: 0,   category: 'Status',   description: 'The user liquefies its body to sharply raise Defense.' },
  'Agility':        { bp: 0,   category: 'Status',   description: 'The user relaxes and lightens its body to sharply raise Speed.' },
  'Air Cutter':     { bp: 55,  category: 'Special',  description: 'The user launches razor-like wind to slash opposing Pokémon. High critical-hit ratio.' },
  'Air Slash':      { bp: 75,  category: 'Special',  description: 'The user attacks with a blade of air. May cause flinching.' },
  'Amnesia':        { bp: 0,   category: 'Status',   description: 'The user temporarily empties its mind to sharply raise Sp. Def.' },
  'Aqua Tail':      { bp: 90,  category: 'Physical', description: 'The user attacks by swinging its tail as if it were a raging wave.' },
  'Attack Order':   { bp: 90,  category: 'Physical', description: 'The user calls out its underlings to attack. High critical-hit ratio.' },
  'Barrier':        { bp: 0,   category: 'Status',   description: 'The user throws up a sturdy wall to sharply raise Defense.' },
  'Blizzard':       { bp: 120, category: 'Special',  description: 'A howling blizzard strikes opposing Pokémon. May freeze the target.' },
  'Body Slam':      { bp: 85,  category: 'Physical', description: 'The user drops onto the target with its full body weight. May cause paralysis.' },
  'Bounce':         { bp: 85,  category: 'Physical', description: 'The user bounces up high, then drops on the target on the second turn. May cause paralysis.' },
  'Brave Bird':     { bp: 120, category: 'Physical', description: 'The user tucks in its wings and charges from a low altitude. Also damages the user.' },
  'Brick Break':    { bp: 75,  category: 'Physical', description: 'The user attacks with a swift chop. Can also break barriers like Reflect and Light Screen.' },
  'Brine':          { bp: 65,  category: 'Special',  description: 'The user attacks with a jet of saltwater. Power doubles if the target\'s HP is half or less.' },
  'Bug Bite':       { bp: 60,  category: 'Physical', description: 'The user bites the target. If the target is holding a Berry, the user eats it and gains its effect.' },
  'Bug Buzz':       { bp: 90,  category: 'Special',  description: 'The user vibrates its wings to generate a damaging sound wave. May lower Sp. Def.' },
  'Bulk Up':        { bp: 0,   category: 'Status',   description: 'The user tenses its muscles to bulk up its body, raising Attack and Defense.' },
  'Calm Mind':      { bp: 0,   category: 'Status',   description: 'The user quietly focuses its mind to raise Sp. Atk and Sp. Def.' },
  'Charm':          { bp: 0,   category: 'Status',   description: 'The user gazes at the target charmingly, sharply lowering its Attack.' },
  'Close Combat':   { bp: 120, category: 'Physical', description: 'The user fights at close range without guarding. Lowers the user\'s Defense and Sp. Def.' },
  'Cosmic Power':   { bp: 0,   category: 'Status',   description: 'The user absorbs a mystical power to raise Defense and Sp. Def.' },
  'Cross Chop':     { bp: 100, category: 'Physical', description: 'The user delivers a double chop with its forearms. High critical-hit ratio.' },
  'Crunch':         { bp: 80,  category: 'Physical', description: 'The user crunches the target with sharp fangs. May lower Defense.' },
  'Dark Pulse':     { bp: 80,  category: 'Special',  description: 'The user releases a horrible aura imbued with dark thoughts. May cause flinching.' },
  'Dig':            { bp: 80,  category: 'Physical', description: 'The user burrows underground on the first turn, then strikes on the next turn.' },
  'Double-Edge':    { bp: 120, category: 'Physical', description: 'A reckless life-risking tackle. Also damages the user considerably.' },
  'Dragon Dance':   { bp: 0,   category: 'Status',   description: 'The user vigorously performs a mystic dance to raise Attack and Speed.' },
  'Dream Eater':    { bp: 100, category: 'Special',  description: 'The user eats the dreams of a sleeping target. Restores HP by half the damage dealt.' },
  'Drill Peck':     { bp: 80,  category: 'Physical', description: 'A corkscrewing attack with a sharp beak acting as a drill.' },
  'Dynamic Punch':  { bp: 100, category: 'Physical', description: 'The user punches extremely hard. Always causes confusion if it hits.' },
  'Earth Power':    { bp: 90,  category: 'Special',  description: 'The user makes the ground under the target erupt with power. May lower Sp. Def.' },
  'Earthquake':     { bp: 100, category: 'Physical', description: 'The user sets off an earthquake that strikes every Pokémon around it.' },
  'Energy Ball':    { bp: 80,  category: 'Special',  description: 'The user draws power from nature and fires it at the target. May lower Sp. Def.' },
  'Extreme Speed':  { bp: 80,  category: 'Physical', description: 'The user charges at blinding speed. This move always goes first.' },
  'Facade':         { bp: 70,  category: 'Physical', description: 'An attack that doubles in power if the user is poisoned, burned, or paralyzed.' },
  'Fake Tears':     { bp: 0,   category: 'Status',   description: 'The user feigns crying to sharply lower the target\'s Sp. Def.' },
  'Feather Dance':  { bp: 0,   category: 'Status',   description: 'The user covers the target\'s body with feathers to sharply lower Attack.' },
  'Fire Blast':     { bp: 120, category: 'Special',  description: 'The target is attacked with an intense blast of all-consuming fire. May burn.' },
  'Flash Cannon':   { bp: 80,  category: 'Special',  description: 'The user gathers all its light energy and releases it at once. May lower Sp. Def.' },
  'Fly':            { bp: 90,  category: 'Physical', description: 'The user flies up into the sky on the first turn, then strikes on the next turn.' },
  'Focus Blast':    { bp: 120, category: 'Special',  description: 'The user heightens its mental focus and unleashes its power. May lower Sp. Def.' },
  'Future Sight':   { bp: 80,  category: 'Special',  description: 'Two turns after this move is used, the target is attacked with a psychic force.' },
  'Growl':          { bp: 0,   category: 'Status',   description: 'The user growls in an endearing way, lowering the target\'s Attack.' },
  'Growth':         { bp: 0,   category: 'Status',   description: 'The user\'s body grows all at once, raising Attack and Sp. Atk.' },
  'Gunk Shot':      { bp: 120, category: 'Physical', description: 'The user shoots filthy garbage at the target. May poison the target.' },
  'Hidden Power':   { bp: 60,  category: 'Special',  description: 'A unique attack that varies in type depending on the Pokémon using it.' },
  'Howl':           { bp: 0,   category: 'Status',   description: 'The user howls loudly to raise its Attack.' },
  'Hydro Pump':     { bp: 120, category: 'Special',  description: 'The target is blasted by a huge volume of water launched under great pressure.' },
  'Iron Defense':   { bp: 0,   category: 'Status',   description: 'The user hardens its body\'s surface to sharply raise Defense.' },
  'Iron Head':      { bp: 80,  category: 'Physical', description: 'The user slams the target with its steel-hard head. May cause flinching.' },
  'Iron Tail':      { bp: 100, category: 'Physical', description: 'The target is slammed with a steel-hard tail. May lower Defense.' },
  'Leer':           { bp: 0,   category: 'Status',   description: 'The user gives the target an intimidating leer that lowers Defense.' },
  'Megahorn':       { bp: 120, category: 'Physical', description: 'Using its tough and impressive horn, the user rams into the target.' },
  'Metal Sound':    { bp: 0,   category: 'Status',   description: 'A horrible sound like scraping metal sharply lowers the target\'s Sp. Def.' },
  'Meteor Mash':    { bp: 100, category: 'Physical', description: 'The target is hit with a hard punch fired like a meteor. May raise Attack.' },
  'Mud-Slap':       { bp: 20,  category: 'Special',  description: 'The user hurls mud in the target\'s face to inflict damage and lower accuracy.' },
  'Muddy Water':    { bp: 95,  category: 'Special',  description: 'The user attacks with muddy water. May lower the target\'s accuracy.' },
  'Nasty Plot':     { bp: 0,   category: 'Status',   description: 'The user stimulates its brain by thinking bad thoughts to sharply raise Sp. Atk.' },
  'Outrage':        { bp: 120, category: 'Physical', description: 'The user rampages for two to three turns, then becomes confused.' },
  'Petal Dance':    { bp: 90,  category: 'Special',  description: 'The user scatters petals for two to three turns, then becomes confused.' },
  'Poison Sting':   { bp: 15,  category: 'Physical', description: 'The user stabs the target with a poisonous stinger. May poison the target.' },
  'Power Whip':     { bp: 120, category: 'Physical', description: 'The user violently whirls its vines or tentacles to harshly lash the target.' },
  'Psychic':        { bp: 90,  category: 'Special',  description: 'The target is hit by a strong telekinetic force. May lower Sp. Def.' },
  'Rock Polish':    { bp: 0,   category: 'Status',   description: 'The user polishes its body to sharply raise Speed.' },
  'Rock Slide':     { bp: 75,  category: 'Physical', description: 'Large boulders are hurled at the target. May cause flinching.' },
  'Rollout':        { bp: 30,  category: 'Physical', description: 'The user rolls into the target for five turns. Power increases each turn.' },
  'Scary Face':     { bp: 0,   category: 'Status',   description: 'The user frightens the target with a scary face to sharply lower Speed.' },
  'Screech':        { bp: 0,   category: 'Status',   description: 'An earsplitting screech harshly lowers the target\'s Defense.' },
  'Shadow Ball':    { bp: 80,  category: 'Special',  description: 'The user hurls a shadowy blob at the target. May lower Sp. Def.' },
  'Shadow Force':   { bp: 120, category: 'Physical', description: 'The user disappears, then strikes the target on the next turn. Hits through Protect.' },
  'Signal Beam':    { bp: 75,  category: 'Special',  description: 'The user attacks with a sinister beam of light. May confuse the target.' },
  'Slam':           { bp: 80,  category: 'Physical', description: 'The target is slammed with a long tail, vines, or the like.' },
  'Sludge Bomb':    { bp: 90,  category: 'Special',  description: 'Unsanitary sludge is hurled at the target. May poison the target.' },
  'Solar Beam':     { bp: 120, category: 'Special',  description: 'The user absorbs light on the first turn, then blasts a beam on the next.' },
  'Stone Edge':     { bp: 100, category: 'Physical', description: 'The user stabs the target from below with sharpened stones. High critical-hit ratio.' },
  'Strength':       { bp: 80,  category: 'Physical', description: 'The target is slugged with a punch thrown at maximum power.' },
  'String Shot':    { bp: 0,   category: 'Status',   description: 'The target is bound with silk blown from the user\'s mouth to lower Speed.' },
  'Struggle':       { bp: 50,  category: 'Physical', description: 'A desperate attack used only when all PP are depleted. Also damages the user.' },
  'Surf':           { bp: 95,  category: 'Special',  description: 'The user attacks everything around it by swamping its surroundings with a giant wave.' },
  'Swords Dance':   { bp: 0,   category: 'Status',   description: 'A frenetic dance to uplift the fighting spirit. Sharply raises Attack.' },
  'Tackle':         { bp: 35,  category: 'Physical', description: 'A physical attack in which the user charges and slams into the target.' },
  'Tail Glow':      { bp: 0,   category: 'Status',   description: 'The user stares at flashing lights to drastically raise Sp. Atk.' },
  'Tail Whip':      { bp: 0,   category: 'Status',   description: 'The user wags its tail cutely, lowering the target\'s Defense.' },
  'Take Down':      { bp: 90,  category: 'Physical', description: 'A reckless, full-body charge attack. Also damages the user a little.' },
  'Thunder':        { bp: 120, category: 'Special',  description: 'A wicked thunderbolt is dropped on the target. May cause paralysis.' },
  'Thunderbolt':    { bp: 95,  category: 'Special',  description: 'A strong electric blast crashes down on the target. May cause paralysis.' },
  'Volt Tackle':    { bp: 120, category: 'Physical', description: 'The user electrifies itself, then charges. Also damages the user considerably.' },
  'Wood Hammer':    { bp: 120, category: 'Physical', description: 'The user slams its rugged body into the target. Also damages the user considerably.' },
  'X-Scissor':      { bp: 80,  category: 'Physical', description: 'The user slashes at the target by crossing its scythes or claws as if they were scissors.' },
  'Zap Cannon':     { bp: 120, category: 'Special',  description: 'The user fires an electric blast like a cannon. Always causes paralysis if it hits.' },
  'Zen Headbutt':   { bp: 80,  category: 'Physical', description: 'The user focuses its willpower to its head and attacks. May cause flinching.' },
  // Status-inflicting moves
  'Thunder Wave':   { bp: 0,   category: 'Status',   description: 'A weak electric charge is launched at the target. It causes paralysis.' },
  'Will-O-Wisp':    { bp: 0,   category: 'Status',   description: 'The user shoots a sinister flame at the target to inflict a burn.' },
  'Toxic':          { bp: 0,   category: 'Status',   description: 'A move that badly poisons the target. Its damage worsens every turn.' },
  'Hypnosis':       { bp: 0,   category: 'Status',   description: 'The user employs hypnotic suggestion to make the target fall asleep.' },
  'Sleep Powder':   { bp: 0,   category: 'Status',   description: 'The user scatters a cloud of sleep-inducing dust around the target.' },
  'Stun Spore':     { bp: 0,   category: 'Status',   description: 'The user scatters a cloud of numbing powder that paralyzes the target.' },
  'Sing':           { bp: 0,   category: 'Status',   description: 'A soothing lullaby is sung in a calming voice that puts the target to sleep.' },
  'Glare':          { bp: 0,   category: 'Status',   description: 'The user intimidates the target with the pattern on its belly to cause paralysis.' },
  'Poison Powder':  { bp: 0,   category: 'Status',   description: 'The user scatters a cloud of poisonous dust that poisons the target.' },
  // Weather moves
  'Rain Dance':     { bp: 0,   category: 'Status',   description: 'The user summons a heavy rain that lasts five turns, powering up Water-type moves.' },
  'Sunny Day':      { bp: 0,   category: 'Status',   description: 'The user intensifies the sun for five turns, powering up Fire-type moves.' },
  'Sandstorm':      { bp: 0,   category: 'Status',   description: 'A sandstorm rages for five turns, hurting all types except Rock, Ground, and Steel.' },
  'Hail':           { bp: 0,   category: 'Status',   description: 'A hailstorm rages for five turns, hurting all types except Ice.' },
  // Hazard moves
  'Stealth Rock':   { bp: 0,   category: 'Status',   description: 'The user lays a trap of levitating stones. Foes take damage on switch-in.' },
  'Spikes':         { bp: 0,   category: 'Status',   description: 'The user lays a trap of spikes. Foes take damage on switch-in.' },
  'Toxic Spikes':   { bp: 0,   category: 'Status',   description: 'The user lays a trap of poison spikes. Foes are poisoned on switch-in.' },
  'Rapid Spin':     { bp: 20,  category: 'Physical', description: 'A spin attack that also removes hazards from the user\'s side.' },
  'Defog':          { bp: 0,   category: 'Status',   description: 'A strong wind clears away hazards, barriers, and fog from both sides.' },
};

export function getMoveInfo(moveName: string): MoveInfo {
  return MOVE_INFO[moveName] ?? { bp: 0, category: 'Physical', description: 'No description available.' };
}
