// Move name → type mapping for TM sprites and display
// Auto-generated by scripts/gen-all-pokemon.js
import type { PokemonType } from './types';

export const MOVE_TYPES: Record<string, PokemonType> = {
  // Normal
  'Body Slam': 'normal',
  'Double-Edge': 'normal',
  'Extreme Speed': 'normal',
  'Facade': 'normal',
  'Hidden Power': 'normal',
  'Slam': 'normal',
  'Strength': 'normal',
  'Struggle': 'normal',
  'Tackle': 'normal',
  'Take Down': 'normal',
  // Fire
  'Fire Blast': 'fire',
  // Water
  'Aqua Tail': 'water',
  'Brine': 'water',
  'Hydro Pump': 'water',
  'Muddy Water': 'water',
  'Surf': 'water',
  // Electric
  'Thunder': 'electric',
  'Thunderbolt': 'electric',
  'Volt Tackle': 'electric',
  'Zap Cannon': 'electric',
  // Grass
  'Energy Ball': 'grass',
  'Petal Dance': 'grass',
  'Power Whip': 'grass',
  'Solar Beam': 'grass',
  'Wood Hammer': 'grass',
  // Ice
  'Blizzard': 'ice',
  // Fighting
  'Brick Break': 'fighting',
  'Close Combat': 'fighting',
  'Cross Chop': 'fighting',
  'Dynamic Punch': 'fighting',
  'Focus Blast': 'fighting',
  // Poison
  'Gunk Shot': 'poison',
  'Poison Sting': 'poison',
  'Sludge Bomb': 'poison',
  // Ground
  'Dig': 'ground',
  'Earth Power': 'ground',
  'Earthquake': 'ground',
  'Mud-Slap': 'ground',
  // Flying
  'Aerial Ace': 'flying',
  'Air Cutter': 'flying',
  'Air Slash': 'flying',
  'Bounce': 'flying',
  'Brave Bird': 'flying',
  'Drill Peck': 'flying',
  'Fly': 'flying',
  // Psychic
  'Dream Eater': 'psychic',
  'Future Sight': 'psychic',
  'Psychic': 'psychic',
  'Zen Headbutt': 'psychic',
  // Bug
  'Attack Order': 'bug',
  'Bug Bite': 'bug',
  'Bug Buzz': 'bug',
  'Megahorn': 'bug',
  'Signal Beam': 'bug',
  'X-Scissor': 'bug',
  // Rock
  'Rock Slide': 'rock',
  'Rollout': 'rock',
  'Stone Edge': 'rock',
  // Ghost
  'Shadow Ball': 'ghost',
  'Shadow Force': 'ghost',
  // Dragon
  'Outrage': 'dragon',
  // Dark
  'Crunch': 'dark',
  'Dark Pulse': 'dark',
  // Steel
  'Flash Cannon': 'steel',
  'Iron Head': 'steel',
  'Iron Tail': 'steel',
  'Meteor Mash': 'steel',
};

export const ALL_MOVE_NAMES = Object.keys(MOVE_TYPES);

export function getMoveType(moveName: string): PokemonType {
  return MOVE_TYPES[moveName] ?? 'normal';
}

export function getTMSprite(moveName: string): string {
  const type = getMoveType(moveName);
  return `/pokemonparty/assets/tm-${type}.png`;
}
